apiVersion: apps/v1
kind: Deployment
metadata:
  name: house-price-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: house-price
  template:
    metadata:
      labels:
        app: house-price
    spec:
      containers:
      - name: house-price
        image: l00187756/house-price:latest
        ports:
        - containerPort: 5000